---
name: Build
on:
  pull_request:
  push:
    branches: [master]
jobs:
  build:
    name: Compile Code
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'noci')"
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest]
        # os: [macOS-latest]
        os: [ubuntu-latest, macOS-latest]
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prereqs
        uses: mstksg/get-package@v1
        with:
          brew: gcc@9 bison flex swig readline libomp
          apt-get: build-essential bison flex swig libreadline-dev libomp-dev
      - name: Build and Install
        run: |
          ./.build.sh
        env:
          # https://codecov.io/gh/Electrostatics/apbs
          CODECOV_TOKEN: "e3a1e24c-5598-4f47-9353-7fa0ac57f98e"
